### ISSUE TITLE
python benchmark.py try to allocate  cuda memory 9177984325.83 GiB

### ISSUE THREAD

**Issue by hailsham** [ClementPinard/Pytorch-Correlation-extension#13]
when I try to run benchmark.py, it raise an error says that 
`RuntimeError: CUDA out of memory. Tried to allocate 9177984325.83 GiB (GPU 0; 5.93 GiB total capacity; 78.25 MiB already allocated; 4.44 GiB free; 0 bytes cached) (malloc at /pytorch/aten/src/THC/THCCachingAllocator.cpp:231)`

here is my environments:
`pytorch 1.0`
`cuda9.0`

Is something wrong?  thanks a lot.

**Comment by ClementPinard** [comment]
That's a lot of gigabytes!

What argument did you call the benchmark with?

What commit are you in? I pushed changes recently

**Comment by hailsham** [comment]
> That's a lot of gigabytes!
> 
> What argument did you call the benchmark with?
> 
> What commit are you in? I pushed changes recently

thanks for reply!  
I simply run `python benchmark.py cuda`, I try `python benchmark.py cpu` and it works fine. 
the commit is `cbe8e21`, I am sure it was latest.   and  my python version is 3.6.

**Comment by ClementPinard** [comment]
I updated the code to work with `int32_t` integers instead of `int64_t`. In addition to being faster, maybe it will solve your problem.
However, when I tested the benchmark in my own machine (python 3.7, pytorch 1.0.1 GTX980Ti) I had no problem. Keep in mind that CUDA_LAUNCH_BLOCKING must be set to 1 before launching the benchmark script

**Comment by hailsham** [comment]
sorry for delay. it still doesn't work, and the error info is the same. by the way, I cannot install the package by `python setup.py install`， but `pip install spatial-correlation-sampler `  is OK. I will carefully checkout my environment, if I find the problem, I will return to report it. thanks for your help!

**Comment by ClementPinard** [comment]
What is the error message when you try to install from source ?

**Comment by hailsham** [comment]
these are some of  error messages, it seems related to pybind11? 
`
...    
/data/miniconda3/envs/torch1_cuda_9/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:206: error: expansion pattern ‘pybind11::detail::negation<std::is_same<pybind11::detail::bools<pybind11::detail::negation<std::is_base_of<pybind11::arg, Args> >::value ..., pybind11::detail::negation<std::is_same<pybind11::detail::kwargs_proxy, Args> >::value ..., true>, pybind11::detail::bools<true, pybind11::detail::negation<std::is_base_of<pybind11::arg, Args> >::value ..., pybind11::detail::negation<std::is_same<pybind11::detail::kwargs_proxy, Args> >::value ...> > >::value’ contains no argument packs
/data/miniconda3/envs/torch1_cuda_9/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:215: error: template argument 1 is invalid
/data/miniconda3/envs/torch1_cuda_9/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:392: error: expansion pattern ‘pybind11::detail::negation<std::is_same<pybind11::detail::bools<pybind11::detail::negation<std::is_base_of<pybind11::arg, Args> >::value ..., pybind11::detail::negation<std::is_same<pybind11::detail::kwargs_proxy, Args> >::value ..., true>, pybind11::detail::bools<true, pybind11::detail::negation<std::is_base_of<pybind11::arg, Args> >::value ..., pybind11::detail::negation<std::is_same<pybind11::detail::kwargs_proxy, Args> >::value ...> > >::value’ contains no argument packs
/data/miniconda3/envs/torch1_cuda_9/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:395: error: template argument 2 is invalid
/data/miniconda3/envs/torch1_cuda_9/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:397: error: template argument 1 is invalid
/data/miniconda3/envs/torch1_cuda_9/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:397: error: template argument 2 is invalid
/data/miniconda3/envs/torch1_cuda_9/lib/python3.6/site-packages/torch/lib/include/pybind11/pytypes.h:1165:412: error: template argument 1 is invalid  
  ...
`

my environment is : 
`
python: 3.6
pytorch: 1.0.1
cuda: 9.0
gcc: 5.5
`

**Comment by ClementPinard** [comment]
can you try to compile the extension-cpp tutorial ? https://github.com/pytorch/extension-cpp

I've never seen bugs with pybind11, so it may be more related to pytorch cpp extension in general than this particular module !

**Comment by hailsham** [comment]
hello! sorry for delay.  I find the solution to problem of ` python setup.py build`, according to [this](https://discuss.pytorch.org/t/compiling-cpp-cuda-extension-composed-of-multiple-files/30685/4),  I comment `#include <torch/extension.h>` in `Correlation_Module/correlation_cuda_kernel.cu` and  replace it with `#include <torch/types.h>`, then it works fine. but it still try to allocate a lot gigabytes when I run `python benchmark.py cuda`, I will keep looking for the solution. thanks.

**Comment by wenxin-bupt** [comment]
> hello! sorry for delay. I find the solution to problem of ` python setup.py build`, according to [this](https://discuss.pytorch.org/t/compiling-cpp-cuda-extension-composed-of-multiple-files/30685/4), I comment `#include <torch/extension.h>` in `Correlation_Module/correlation_cuda_kernel.cu` and replace it with `#include <torch/types.h>`, then it works fine. but it still try to allocate a lot gigabytes when I run `python benchmark.py cuda`, I will keep looking for the solution. thanks.

works for me. thx!

**Comment by ClementPinard** [comment]
pushed changes to fix the issue

**Comment by XiaoXueHou** [comment]
@hailsham 朋友你好！很抱歉时隔这么久还在这个Issue中打扰你~我在安装“spatial-correlation-sampler”库时遇到了比较棘手的问题，然后我发现你当时的environments和我的很相似。所以冒昧打扰，希望能够得到你的指点和帮助。我的environments是：Python3.6、Pytorch1.0.1、CUDA9.0、gcc5.4.0，当我使用“pip install spatial-correlation-sampler”进行安装时，会报错如图1。当我使用"python setup.py install"进行安装时，会报错如图2。我也发布了新的Issue以期获得作者的帮助，但是可能是由于问题表达不够清晰，作者提出的方案未能解决我的问题。在寻找解决办法时，无意发现了我们environments比较相似，而且国内朋友可以更清晰地阐明问题。期待能够得到你的帮助~
图①：
![image](https://user-images.githubusercontent.com/37476521/115194120-96bda080-a11f-11eb-8f57-a763dd0a0322.png)
![image](https://user-images.githubusercontent.com/37476521/115194141-9f15db80-a11f-11eb-8932-f3b090fe49f4.png)
![image](https://user-images.githubusercontent.com/37476521/115194195-b1901500-a11f-11eb-90cc-7bdd61a0a084.png)
图②：
![image](https://user-images.githubusercontent.com/37476521/115194299-da180f00-a11f-11eb-8199-b039013e8be5.png)
